Clarify android manifest override logic
There was a build error apparently due to the latest rnfirebase
update (12.9.3) which seems to have a newly set default value
for adId usage. We need to override this to disable tracking.
Error: https://github.com/mapswipe/mapswipe/runs/3989314393?check_suite_focus=true#step:16:471